server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://132.232.117.84:3306/heima
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  type-aliases-package: com.leyou.order.pojo


ly:
  jwt:
    pubKeyPath: C:/Users/chenyilei/Desktop/SteamAnd Vm/rsa.pub # 公钥地址
    cookie-name: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1