server:
  port: 10086

spring:
  application:
    name: ly-register
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000


