server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 132.232.117.84

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
ly:
  jwt:
    pubKeyPath: C:/Users/chenyilei/Desktop/SteamAnd Vm/rsa.pub # 公钥地址
    cookie-name: LY_TOKEN