spring:
  application:
    name: goods-page
  thymeleaf:
    cache: false
  rabbitmq:
    host: 132.232.117.84
    username: root
    password: root
    virtual-host: /leyou


server:
  port: 8084
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port}
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期