server:
  port: 10010

spring:
  application:
    name: api-gateway
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}

    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  routes:
    item-service: /item/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
  prefix: /api # 添加路由前缀
  retryable: true
  sensitive-headers:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7100
  metrics:
    enabled: true
ribbon:
  ReadTimeout: 7000
  ConnectTimeout: 5000


ly:
  jwt:
    pubKeyPath: C:/Users/chenyilei/Desktop/SteamAnd Vm/rsa.pub # 公钥地址
    cookie-name: LY_TOKEN
    filter:
      - /api/auth
      - /api/user/register
      - /api/user/code
      - /api/user/check
      - /api/search
      - /api/item
