server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://132.232.117.84:3306/heima
    username: root
    password: root
  rabbitmq:
    host: 132.232.117.84
    username: root
    password: root
    virtual-host: /leyou

    publisher-confirms: true
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: ly.item.exchange


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    instance-info-replication-interval-seconds= 10 # 上传信息时间
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

